### ISSUE TITLE
View-model tab data tree collapses on update

### ISSUE THREAD

**Issue by malx122** [Polyjuice/starcounter-debug-aid#18]
Every time there is a message from server, no matter if there is an update or not the data tree in the view-model tab collapses. Really annoying if you like us, pinging the server for changes every minute.

I don't think its needed to collapse it even if there IS an update...

(I'm guessing the data tree is actually refreshed/replaced and not collapsed)

**Comment by warpech** [comment]
`juicy-jsoneditor` uses `josdejong/jsoneditor` from this fork: https://github.com/tomalec/jsoneditor/tree/102-onChangeArgumentsBuilt

Maybe in the upstream repo (josdejong/jsoneditor) this problem was already fixed? If not, maybe we could propose a fix there?

**Comment by miyconst** [comment]
I have tried two approaches:

### Save & restore expanded state
1. Added methods `getExpanded` & `setExpanded`. The methods return/accept json-tree state for all nodes. 
2. Save expanded state before `editor.set(json)` and apply it back after setting the json value.
3. Do the same for the parent container scroll position.

This works, but not as expected. jsoneditor completely removes DOM and creates it again in `set` method. In the result the tree flashes on each refresh.

### Do not recreate entire tree on json apdate
1. Added method `applyJson`. The method iterates through each property in the new json and compares it to existing tree-model.
2. Removes unnecessary nodes, adds new nodes and refreshes value of existing nodes.
3. This works as long as we don't change type of a property. If an object `{}` became an array `[]` it does not work properly.

I have also inspected the main branch of the jsoneditor from here:
https://github.com/josdejong/jsoneditor
It does not refresh values if json object was changed and aslo removes entire DOM element in `set` method.

There is no commits so far.

**Comment by malx122** [comment]
Any updates?
Please just at least add a pause button that just make it freeze or something like that.
It is impossible to use for us at the moment.

**Comment by miyconst** [comment]
@warpech I have implemented the first way (*Save & restore expanded state*), there is no blinking with the new branch of `jsoneditor`.

The collapse/expand state is saved per node by it's order, this may lead to some unexpected behaviour when some nodes added/removed.

Could you please check how it works (the simplest way would be the Chatter app) and update installation if it is good.

Still not perfect, but better than nothing.

**Comment by miyconst** [comment]
Ping @warpech.

**Comment by warpech** [comment]
Reviewing

**Comment by warpech** [comment]
Looks good for me, apart from https://github.com/Polyjuice/starcounter-debug-aid/issues/31 - which is not a big deal.

**Comment by miyconst** [comment]
I have added some workaround for #31, closing this issue.
