### ISSUE TITLE
Display history of patch requests and responses

### ISSUE THREAD

**Issue by warpech** [Polyjuice/starcounter-debug-aid#19]
Add a tab called "History" that displays the history of all sent and received JSON Patches (both HTTP PATCH and WebSocket)

**Comment by warpech** [comment]
It should have a form of a table (maybe with expandable rows, maybe with [`<hot-table>`](http://handsontable.github.io/hot-table/)?) with the following information:

- patch body
- information whether it is incoming or outgoing patch
- information about the protocol (WebSocket or HTTP)
  - for HTTP requests, the URL of the request
- time of the request (hh:mm:ss.mmm)
- duration of the request

Not all of the above information needs to be displayed simultaneously but it should be accessible somehow.

*In future, not for this task*: there may be a button which shows the state of the puppet `obj` at that time. We don't even need to make snapshots of the object. Just store the original object and apply the incoming and outgoing patches from the log. Then they would need to be applied in real order in which  they were created.

**Comment by warpech** [comment]
:information_source: Information about PuppetJS:
https://github.com/PuppetJs/PuppetJs/wiki/Server-communication
https://github.com/PuppetJs/PuppetJs/wiki/Server-communication:-advanced-synchronization

**Comment by miyconst** [comment]
@warpech, the Network tab with incoming/outcoming patches is ready: https://github.com/Polyjuice/starcounter-debug-aid/issues/20

There are some differences compare to your description:
- Time is not only time, but full date and time. Might be easily changed if needed.
- No duration of the request. Do we really need it? How to calculate duration of websocket requests? The next received message is not necessary the response for the last send message.
- The patch body is not only displayed, but also available in json-editor readonly mode.

**Comment by miyconst** [comment]
Closing this issue.
The Network tab is already implemented.
