### ISSUE TITLE
HTTP icon not displayed for patch requests

### ISSUE THREAD

**Issue by warpech** [Polyjuice/starcounter-debug-aid#26]
As seen in the attached screenshot, the HTTP icon is not displayed for the requests 5 and 6

![network](https://cloud.githubusercontent.com/assets/566463/7135875/6296a038-e2ab-11e4-80f9-dc3d6794fa66.png)

**Comment by miyconst** [comment]
This bug already fixed, but not in build, I guess.

**Comment by warpech** [comment]
Sorry, my bad. I updated the version used in https://github.com/Starcounter/Starcounter/tree/develop/src/BuildSystem/Polyjuice

**Comment by miyconst** [comment]
It's okay. Anyway, the icon will be removed from there.
