### ISSUE TITLE
Add the HTTP method in the "Network" tab

### ISSUE THREAD

**Issue by warpech** [Polyjuice/starcounter-debug-aid#27]
In the network tab, there should be a HTTP method displayed before the request URL:

![network](https://cloud.githubusercontent.com/assets/566463/7135890/8e474638-e2ab-11e4-99f2-66816b0e894a.png)

I suggest to reorder the columns:

1. # (number)
2. Time (the date should be displayed only in a "title" tooltip)
3. Type, which can be "WS" or the method name in case of a HTTP method:
 - WS
 - GET
 - POST
 - PATCH
 - *etc*
4. URL which is a link (the protocol, host and port is not displayed)

As for the graphic icon, I think it is actually not needed if we display the above string. For requests we can display a green → after the method name (for responses a red ← RESPECTIVELY)

**Comment by miyconst** [comment]
Done, now *Network* tab renamed to *Patches* and looks like this:
![patches-tab](https://cloud.githubusercontent.com/assets/6435556/7140877/9dfa509a-e2d6-11e4-96c2-a9e16130f1b9.PNG)
