### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by tomalec** [Polyjuice/starcounter-debug-aid#30]
Most of the features does not work in IE.
The first issue that I encounter is that 
```html
<template id="row">
  <tr>
    <td>
      <span class="file"></span>
    </td>
    <td>
      <a class="path"></a>
      <span class="error"></span>
    </td>
    <td class="bowerCell"></td>
  </tr>
</template>
```
content is parsed in IE as 
```html
      <span class="file"></span>
      <a class="path"></a>
      <span class="error"></span>
```

**Comment by warpech** [comment]
This particular problem can be solved by following the text at the page: https://www.polymer-project.org/0.5/docs/polymer/databinding-compat.html
