### ISSUE TITLE
"Preserve settings" checkbox

### ISSUE THREAD

**Issue by warpech** [Polyjuice/starcounter-debug-aid#32]
Personally I dislike the fact that settings are remembered between page loads. Multiple times it caused me problems and unnecessary bug searches, just because I forgot that I have WebSocket turned off. 

I know this feature can be useful to someone, so I propose to add another checkbox called "Preserve starcounter-debug-aid settings upon navigation"

![screenshot 2015-06-25 16 10 10](https://cloud.githubusercontent.com/assets/566463/8356284/ab688498-1b54-11e5-8783-83ef955f5ae6.png)

**Comment by miyconst** [comment]
Should the `"Preserve starcounter-debug-aid settings upon navigation"` value be saved between page loads :laughing:? Just kidding, I will do the checkbox.

**Comment by warpech** [comment]
Yes it should :D

I forgot to add, I propose this checkbox to be OFF by default.

**Comment by miyconst** [comment]
Done together with https://github.com/Polyjuice/starcounter-debug-aid/issues/33.
