### ISSUE TITLE
Cosmetic changes to settings

### ISSUE THREAD

**Issue by warpech** [Polyjuice/starcounter-debug-aid#33]
1. The checkboxes related to PuppetJs should be put under a common header "Puppet settings"
2. "WebSocket" should be changed to "Enable WebSocket"
3. "Morph URL" should be changed to "Enable URL morphing"
4. Each setting should be on a separate line
5. Each setting should have a title that explains consequences of unchecking it

**Comment by miyconst** [comment]
Done, looks like this:
![sdi-settings](https://cloud.githubusercontent.com/assets/6435556/8373032/872405a6-1bf1-11e5-940a-b86a5c059994.png)

**Comment by warpech** [comment]
nice!

--
Marcin Warpechowski
+48 603 607 801
