### ISSUE TITLE
Element does not work with ShadyDOM

### ISSUE THREAD

**Issue by tomalec** [Polyjuice/starcounter-debug-aid#35]
`.shadowRoot`  reference couses errors, when used in ShadyDOM mode.

Even if Launcher, and juicy- custom elements requires Shadow DOM, we could imagine the case of Starcounter App that uses only webcomponents polyfill, puppet-client, starcounter-debug-aid, and it is supposed to work in browser without SD.

**Comment by miyconst** [comment]
Fixed, the element works in shady dom now, but the `juicy-jsoneditor` looks ugly.
